# Project information
site_name: Avoid conda licensing issues
site_author: Jacques Dainat et al.
site_url: https://mivegec.pages.ird.fr/dainat/malbec-fix-conda-licensing-issues
site_description: Avoid conda licensing issues
site_dir: public # When you build your site, all of the files are written to the directory assigned to the site_dir configuration option (defaults to "site")

# Repository
repo_name: 'malbec-fix-conda-licensing-issues'
repo_url: 'https://forge.ird.fr/mivegec/dainat/malbec-fix-conda-licensing-issues'
edit_uri: edit/main/docs/ # Allow to replace edit/master/docs use by default

# Configuration
theme:
  language: en  # default language
  name: material
  home: en/index.md
  logo: images/IRD.png # logo top left page
  search_index_only: true
  include_search_page: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # collapse subsections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # remove table of content on the right side
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - tables
  - toc:
      permalink: '#'

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - macros

# Customization
extra:
  homepage: en/ # Page displayed when clicking the logo
  history_buttons: false
  # --- set whole scope variables ---
  contact: jacques.dainat@ird.fr
  institute: IRD
  unit: MIVEGEC
  repo: https://forge.ird.fr/mivegec/dainat/malbec-fix-conda-licensing-issues
  color_table_header: "#333a99"

  # --- set alternative languages ---
  alternate:
    - name: English
      link: en/ 
      lang: en
    - name: Français
      link: fr/
      lang: fr

# Customization
extra_css: 
  - extra.css

# page tree
nav:
  - Home (English):
      - Home: en/index.md
      - Conda distributions: en/pages/conda-distrib.md
      - Licensed channels: en/pages/conda-channels.md
      - Install conda without license problems : en/pages/conda-installation.md
      - Check your installation for licensing problems: en/pages/conda-check.md
      - Sharing environments, avoiding licensing problems: en/pages/conda-share.md    
  - Accueil (Français):
      - Accueil: fr/index.md
      - Les distributions de conda: fr/pages/conda-distrib.md
      - Les canaux sous license: fr/pages/conda-channels.md
      - Installer conda sans problème de license : fr/pages/conda-installation.md
      - Verifier les problèmes de license de son installation: fr/pages/conda-check.md
      - Partage d'environnement, éviter les problèmes de license: fr/pages/conda-share.md