# Project information
site_name: Avoiding the Pitfalls of the Anaconda License
site_author: Jacques Dainat et al.
site_url: https://juke34.github.io/fix-anaconda-licensing-issues/en/
site_description: Avoid conda licensing issues
site_dir: public # When you build your site, all of the files are written to the directory assigned to the site_dir configuration option (defaults to "site")

# Repository
repo_name: 'fix-anaconda-licensing-issues'
repo_url: 'https://github.com/Juke34/fix-anaconda-licensing-issues'
edit_uri: edit/main/docs/ # Allow to replace edit/master/docs use by default

# Configuration
theme:
  language: en  # default language
  name: material
  logo: images/IRD.png # logo top left page
  search_index_only: true
  include_search_page: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # collapse subsections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # remove table of content on the right side
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - tables
  - toc:
      permalink: '#'

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - external-markdown # Package mkdocs-embed-external-markdown /!\ has to be set before macros
  - include-markdown # Package mkdocs-include-markdown-plugin
  - macros

# Customization
extra:
  homepage: en/ # Page displayed when clicking the logo
  history_buttons: false
  # --- set whole scope variables ---
  contact: jacques.dainat@ird.fr
  institute: IRD
  unit: MIVEGEC
  repo: https://github.com/Juke34/fix-anaconda-licensing-issues
  color_table_header: "#333a99"
  anaconda_channels:  "defaults, main, anaconda, free, r, mro, pro, archive, mro-archive, msys2"

  # --- set alternative languages ---
  alternate:
    - name: English
      link: en/ 
      lang: en
    - name: Français
      link: fr/
      lang: fr

# Customization
extra_css: 
  - extra.css

# page tree
nav:
  - Home (English):
      - Home: en/index.md
      - Conda distributions: en/pages/conda-distrib.md
      - Licensed channels: en/pages/conda-channels.md
      - Installing conda: en/pages/conda-installation.md
      - Check and fix your installation: en/pages/conda-check.md
      - Sharing environments: en/pages/conda-share.md  
      - Block access to licensed channels: en/pages/conda-block.md  
      - When installing packages: en/pages/conda-install-package.md
  - Accueil (Français):
      - Accueil: fr/index.md
      - Les distributions de conda: fr/pages/conda-distrib.md
      - Les canaux sous license: fr/pages/conda-channels.md
      - Installer conda: fr/pages/conda-installation.md
      - Verifier et corriger son installation: fr/pages/conda-check.md
      - Partage d'environnement: fr/pages/conda-share.md
      - Bloquer l'accès aux canaux sous licence: fr/pages/conda-block.md  
      - Lors de l'installation de paquets: fr/pages/conda-install-package.md